module.exports = [
  {
    ID: 'seed-001',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    publish_date: '1813-01-28',
    category: 'Classics',
    image: 'https://www.indigo.ca/cdn/shop/files/1_5450a408-e7a5-4d25-946d-f8106ded56f2.jpg?v=1772865198',
    abstract: 'A witty and enduring novel about love, social expectations, and personal growth.',
    contact: 'Library Admin',
    phone: '123-456-7890',
    email: 'library@example.com',
    status: 'available',
    borrowedBy: null
  },
  {
    ID: 'seed-002',
    title: 'Moby-Dick',
    author: 'Herman Melville',
    publish_date: '1851-10-18',
    category: 'Classics',
    image: 'https://m.media-amazon.com/images/I/91xNmlf86yL.jpg',
    abstract: 'Captain Ahab obsessively pursues the great white whale across the seas.',
    contact: 'Library Admin',
    phone: '123-456-7890',
    email: 'library@example.com',
    status: 'available',
    borrowedBy: null
  },
  {
    ID: 'seed-003',
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    publish_date: '1892-10-14',
    category: 'Mystery',
    image: 'https://m.media-amazon.com/images/I/81tNnqcHxlL._AC_UF1000,1000_QL80_.jpg',
    abstract: 'Twelve classic detective stories featuring Sherlock Holmes and Dr. Watson.',
    contact: 'Library Admin',
    phone: '123-456-7890',
    email: 'library@example.com',
    status: 'available',
    borrowedBy: null
  },
  {
    ID: 'seed-004',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    publish_date: '1818-01-01',
    category: 'Science',
    image: 'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781982146160/frankenstein-9781982146160_hr.jpg',
    abstract: 'A groundbreaking tale exploring science, ambition, and responsibility.',
    contact: 'Library Admin',
    phone: '123-456-7890',
    email: 'library@example.com',
    status: 'available',
    borrowedBy: null
  },
  {
    ID: 'seed-005',
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    publish_date: '1883-11-14',
    category: 'Fiction',
    image: 'https://cloud.firebrandtech.com/api/v2/image/111/9780785848837/CoverArtHigh/XL',
    abstract: 'A thrilling adventure of pirates, hidden treasure, and high-seas danger.',
    contact: 'Library Admin',
    phone: '123-456-7890',
    email: 'library@example.com',
    status: 'available',
    borrowedBy: null
  },
  {
    ID: 'seed-006',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    publish_date: '1847-10-16',
    category: 'Romance',
    image: 'https://cdn.kobo.com/book-images/df8380db-fd22-49b6-ad29-97ba56a5d7f6/1200/1200/False/jane-eyre-351.jpg',
    abstract: 'An influential novel of resilience, independence, and enduring love.',
    contact: 'Library Admin',
    phone: '123-456-7890',
    email: 'library@example.com',
    status: 'available',
    borrowedBy: null
  },
  {
    ID: 'seed-007',
    title: 'Walden',
    author: 'Henry David Thoreau',
    publish_date: '1854-08-09',
    category: 'Self-Help',
    image: 'https://cdn.kobo.com/book-images/a0bb1f82-4912-4ba8-afd3-aa5d223d57ff/1200/1200/False/walden-55.jpg',
    abstract: 'Reflections on simple living, self-reliance, and nature.',
    contact: 'Library Admin',
    phone: '123-456-7890',
    email: 'library@example.com',
    status: 'available',
    borrowedBy: null
  },
  {
    ID: 'seed-008',
    title: 'The Wonderful Wizard of Oz',
    author: 'L. Frank Baum',
    publish_date: '1900-05-17',
    category: 'Fantasy',
    image: 'https://m.media-amazon.com/images/I/81JZiBWFR5L._UF1000,1000_QL80_.jpg',
    abstract: 'Dorothy journeys through the magical land of Oz seeking a way home.',
    contact: 'Library Admin',
    phone: '123-456-7890',
    email: 'library@example.com',
    status: 'available',
    borrowedBy: null
  }
];
